### ISSUE TITLE
Python version? 

### ISSUE THREAD

**Issue by kulalsk2** [Eurus-Holmes/SynthText_CH#3]
Can i please know which python you are using and IDE you used to do this?

**Comment by kulalsk2** [comment]
Thanks for replying , I tried with VsCode in Anaconda environment with different version of python but It was giving numerous error, So thought of using same environment as yours, Can I please know the development platform like Windows or Ubuntu?

**Comment by Eurus-Holmes** [comment]
ubuntu 18.01
